# TODO 1: USERNAME AND FILE SETUP FOR DATABASE AND KEEP TRACK OF BOOK READING

# TODO 2: GOALS FOR THE USER EG//BOOKS PER YEAR

# TODO 3: TRACK DAILY PROGRESS (BOOK TITLE, PAGES, HOURS)

# TODO 4: STATISTICS (%READ OF THE BOOK, GOAL PROGRESS, HOW MANY BOOKS/PAGES READ, PAGES/MIN)
